/**
 * Generate the Tailwind theme and the semantic utility layer from design/tokens.ts.
 *
 * Why this exists: until now the palette lived in TWO hand-maintained places — the
 * `colors` object in design/tokens.ts (read by deck.gl, which cannot consume CSS
 * variables) and a hand-typed `@theme` block in app/globals.css (read by the DOM).
 * Keeping two copies of a palette correct by discipline is a standing hazard, and
 * UI polish P1 makes it much worse: it adds a whole type scale, a spacing base and
 * three glass values that would otherwise each have to be typed twice.
 *
 * IMPLEMENTATION_PLAN.md describes a `tailwind.config.ts` importing from tokens.ts.
 * That file never existed and should not — this is Tailwind v4, where the theme is
 * CSS. This script is the v4-shaped version of the same intent.
 *
 *   npm run theme      (also runs automatically before `npm run dev` and `npm run build`)
 *
 * Output app/theme.generated.css is COMMITTED, so a clone builds without running it.
 * Never edit that file; edit design/tokens.ts and regenerate.
 *
 * Node 24 strips TypeScript types natively, so this imports tokens.ts directly rather
 * than parsing it. That is what makes "one source" literally true instead of aspirational.
 */

import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  canvasAtmosphere,
  colors,
  fonts,
  glassMaterial,
  layout,
  motion,
  radius,
  spacing,
  type as typeScale,
} from '../design/tokens.ts';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'app', 'theme.generated.css');

const kebab = (value) => value.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/**
 * Two token names do not map mechanically to their CSS custom property.
 *
 * `surfaceRaised` would kebab to `surface-raised`, but every component in the app
 * already writes `var(--color-raised)`, and `onSurface` would become `on-surface`
 * against an existing `--color-onsurface`. Renaming either would be a pointless sweep
 * across ten files, so the exceptions are declared here rather than pretended away.
 */
const COLOR_ALIASES = { surfaceRaised: 'raised', onSurface: 'onsurface' };
const colorVar = (key) => `--color-${COLOR_ALIASES[key] ?? kebab(key)}`;

const colorBlock = Object.entries(colors)
  .map(([key, hex]) => `  ${colorVar(key)}: ${hex};`)
  .join('\n');

/**
 * Tailwind v4 reads `--text-<name>` plus its three modifier properties and emits a
 * real `text-<name>` utility carrying size, leading, tracking and weight together.
 * That is the whole point of decision 3 in UI_POLISH_PLAN.md §4.1: once a component
 * says `text-body-md` instead of `text-[13px]`, moving the type scale in tokens.ts
 * actually moves the interface.
 */
const typeBlock = Object.entries(typeScale)
  .map(
    ([key, value]) => `  --text-${kebab(key)}: ${value.size}px;
  --text-${kebab(key)}--line-height: ${value.leading};
  --text-${kebab(key)}--letter-spacing: ${value.tracking};
  --text-${kebab(key)}--font-weight: ${value.weight};`,
  )
  .join('\n');

const css = `/* GENERATED by scripts/build-theme.mjs from design/tokens.ts — do not edit.
   Change a value in design/tokens.ts (which mirrors DESIGN.md) and run \`npm run theme\`.
   DESIGN.md is authoritative; tokens.ts mirrors it; this file is derived from tokens.ts. */

@theme {
${colorBlock}

  --font-sans: ${fonts.sans};
  --font-condensed: ${fonts.condensed};
  --font-mono: ${fonts.mono};

${typeBlock}

  /* Tailwind v4 multiplies this single base for p-*, gap-*, m-* and friends, so the
     4px grid from tokens.ts becomes the only spacing available:
       p-1 = ${spacing.xs}px xs · p-2 = ${spacing.sm}px sm · p-3 = ${spacing.md}px md ·
       p-5 = ${spacing.lg}px lg · p-8 = ${spacing.xl}px xl */
  --spacing: ${spacing.xs}px;

  --radius-none: ${radius.none}px;
  --radius-sm: ${radius.sm}px;
  --radius-md: ${radius.md}px;
  --radius-full: ${radius.full}px;

  /* State changes only. Explanatory motion (--ease plus the explain durations) is
     applied per-feature, never globally — see DESIGN.md "Motion" and ADR 0005. */
  --duration-fast: ${motion.fast}ms;
  --duration-medium: ${motion.medium}ms;
  --duration-explain-fast: ${motion.explainFast}ms;
  --duration-explain-slow: ${motion.explainSlow}ms;
  --ease-chart: ${motion.easing};

  --spacing-inspector: ${layout.inspectorWidth}px;
  --spacing-topbar: ${layout.topBarHeight}px;
  --spacing-timeline: ${layout.timelineHeight}px;
  --spacing-profile-chart: ${layout.profileChartHeight}px;
}

/* Materials and atmosphere. Not colours, so they cannot live in @theme, but they are
   token-derived all the same and must not be retyped at a call site. */
:root {
  --glass-alpha: ${glassMaterial.alpha};
  --glass-blur: ${glassMaterial.blurPx}px;
  --grain-amplitude: ${canvasAtmosphere.grainAmplitude};
  --vignette-strength: ${canvasAtmosphere.vignetteStrength};

  /* Desaturated fractal noise, inline so it costs no request and cannot 404 during a
     recording. feColorMatrix saturate=0 is what makes it LUMINANCE grain — coloured
     noise over a canvas whose colours all mean something would be a lie about the data. */
  --grain-texture: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='128' height='128'%3E%3Cfilter id='g'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='3' stitchTiles='stitch'/%3E%3CfeColorMatrix type='saturate' values='0'/%3E%3C/filter%3E%3Crect width='128' height='128' filter='url(%23g)'/%3E%3C/svg%3E");
}

/* ------------------------------------------------------------------------------
   Semantic utilities.

   These carry the parts of a token that Tailwind's generated utilities cannot: a
   font family paired with its OpenType features, and the two canvas atmosphere
   overlays. Everything expressible as a Tailwind utility is left to Tailwind.
   ------------------------------------------------------------------------------ */

@layer components {
  /* Uppercase set at default tracking looks broken rather than emphatic. */
  .label-caps {
    font-family: var(--font-condensed);
    font-size: var(--text-label-caps);
    font-weight: var(--text-label-caps--font-weight);
    line-height: var(--text-label-caps--line-height);
    letter-spacing: var(--text-label-caps--letter-spacing);
    text-transform: uppercase;
    font-feature-settings: 'case' 1;
    color: var(--color-secondary);
  }

  /* Monospace with tabular figures and a slashed zero. Load-bearing, not stylistic:
     a column of latitudes must align on the decimal, a readout that changes every
     frame must not reflow, and O-versus-0 in a WMO id costs a scientist real time.
     Pair with a text-data-* size utility; this class carries family and features only. */
  .data {
    font-family: var(--font-mono);
    font-feature-settings: 'tnum' 1, 'zero' 1;
    font-variant-numeric: tabular-nums slashed-zero;
  }

  /*
   * Glass — the boundary material, and the ONLY translucency in the system.
   *
   * Permitted exclusively on surfaces that sit OVER the canvas, because what shows
   * through them is literally the ocean. Never on the inspector, a Panel, a readout
   * grid or the header: glassing an instrument surface makes it look like a consumer
   * dashboard and contradicts the whole austere-chrome/cinematic-canvas thesis.
   *
   * The alpha floor in tokens.ts is legibility, not taste — below ~0.65 a bright
   * cluster behind the glass wins against text sitting on it.
   */
  .glass {
    background: color-mix(in srgb, var(--color-glass) calc(var(--glass-alpha) * 100%), transparent);
    backdrop-filter: blur(var(--glass-blur)) saturate(0.9);
    -webkit-backdrop-filter: blur(var(--glass-blur)) saturate(0.9);
  }

  /* The lit chamfer where the instrument's case meets its window. Roughly four edges
     in the entire application — using it as a general border flattens the one
     distinction this design system exists to make. */
  .hud-edge-t {
    border-top: 1px solid var(--color-hud-edge);
  }
  .hud-edge-b {
    border-bottom: 1px solid var(--color-hud-edge);
  }

  /*
   * Canvas atmosphere. INSIDE the WebGL viewport and nowhere else — applying either
   * of these to a panel is the single most damaging mistake available here.
   *
   * pointer-events: none is load-bearing, not hygiene. Picking a 2px measurement out
   * of the point cloud goes through the DOM, so an overlay that swallows the click
   * kills selection outright and the UI verification script's framebuffer-scan-then-
   * click check fails with it. See UI_POLISH_PLAN.md §3.5.
   */
  .atmosphere {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }

  /* Luminance grain. Breaks 8-bit banding in the near-black where the deep water sits.
     Amplitude is capped in tokens.ts at the point where it would start competing with
     the dimmest measurements, which is the one thing it must never do.

     'screen', not 'overlay': overlay preserves blacks almost exactly, so over a
     near-black ocean it would do nothing at all — which is the one region the grain
     exists to serve. screen lifts, so the noise reads in the dark and is negligible
     against a lit cluster. */
  .grain {
    opacity: var(--grain-amplitude);
    background-image: var(--grain-texture);
    background-repeat: repeat;
    background-size: 128px 128px;
    mix-blend-mode: screen;
  }

  /*
   * Loading shimmer. See components/ui/Skeleton.tsx for why it is explanatory rather
   * than decorative.
   *
   * The sweep is a transform on a pseudo-element — never background-position, never
   * width. Those animate on the main thread, and chrome that stutters while the canvas
   * is busy undermines the 60k-at-60fps claim in the most visible way available.
   */
  .skeleton {
    position: relative;
    overflow: hidden;
  }
  .skeleton::after {
    content: '';
    position: absolute;
    inset: 0;
    background: linear-gradient(
      90deg,
      transparent,
      color-mix(in srgb, var(--color-border) 85%, transparent),
      transparent
    );
    transform: translateX(-100%);
    animation: skeleton-sweep var(--duration-explain-slow) var(--ease-chart) infinite;
  }

  /* Corner falloff. Seats the HUD readouts that sit in the corners; strength is capped
     below the point where it would begin hiding measurements near the frame edge
     rather than merely darkening the ground behind them. */
  .vignette {
    background: radial-gradient(
      ellipse 75% 75% at 50% 50%,
      transparent 40%,
      color-mix(in srgb, #000 calc(var(--vignette-strength) * 100%), transparent) 100%
    );
  }
}

/* Outside the layer: @keyframes is not a style rule and gains nothing from being in
   one. transform only — see DESIGN.md "Motion" and ADR 0005. */
@keyframes skeleton-sweep {
  to {
    transform: translateX(100%);
  }
}
`;

await writeFile(OUT, css, 'utf8');
console.log(
  `app/theme.generated.css ← design/tokens.ts ` +
    `(${Object.keys(colors).length} colours, ${Object.keys(typeScale).length} type steps)`,
);
