/**
 * Satellite basemap - NASA Blue Marble, topography and bathymetry.
 *
 * A single BitmapLayer rather than a tile pyramid, and that is a consequence of the
 * view rather than a shortcut. `MapCanvas` renders an OrbitView, whose world
 * coordinates ARE degrees of longitude and latitude, so an equirectangular image maps
 * onto [-180, -90, 180, 90] with zero reprojection error. Web-Mercator tiles from
 * Carto or Esri would have to be un-projected per tile and would still need a network
 * the rest of this build deliberately does not need. See docs/adr/0004.
 *
 * The image is served from public/basemap/ and generated by `npm run basemap`.
 */

import { BitmapLayer } from '@deck.gl/layers';
import { registerLayer } from './registry';
import { BASEMAP_BOUNDS, BASEMAP_PARAMETERS } from './basemapShared';

export const basemapSatellite = registerLayer({
  id: 'basemap-satellite',
  label: 'Satellite basemap',
  supports: () => true,
  build: (ctx) => {
    if (ctx.basemap !== 'satellite') return null;
    return new BitmapLayer({
      id: 'basemap-satellite',
      // A constant string, so deck.gl loads it once and never refetches. Passing the
      // URL rather than fetching in React also keeps network access out of the
      // component tree (CLAUDE.md rule 4).
      image: '/basemap/earth-bathy.jpg',
      bounds: BASEMAP_BOUNDS,
      // Photographic imagery is far more saturated than anything else on this canvas.
      // Held well back so the measurements stay the brightest thing in the frame.
      opacity: 0.55,
      parameters: BASEMAP_PARAMETERS,
    });
  },
});
